### ISSUE TITLE
tele获取的图片保存失败

### ISSUE THREAD

**Issue by LHXCxyw** [Feiyuyu0503/free-dall-e-proxy#14]
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/98746227/716d12ac-1b31-42e1-a22a-c4243426338b)
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/98746227/8019557d-4910-4f5d-bbb1-13cd96be2b22)

图片已经发送成功，但是在服务器保存时大小始终为0

**Comment by Feiyuyu0503** [comment]
你是如何部署的，有没有运行日志

**Comment by LHXCxyw** [comment]
docker部署
请求日志如下
[dalle-json.log](https://github.com/Feiyuyu0503/free-dall-e-proxy/files/14393738/dalle-json.log)

**Comment by Feiyuyu0503** [comment]
看起来是图片下载超时了。你是国外服务器还是使用的代理？TIMEOUT设置多少，多试试。

**Comment by LHXCxyw** [comment]
这是香港的服务器，能够正常连接telegram，TIMEOUT我设置了300，还需要设置更大吗

**Comment by LHXCxyw** [comment]
我在重启docker后日志显示到这一步就会卡住，网页也无法访问，请问是什么原因
![IMG_20240225_014734](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/98746227/4d7ee862-7720-4e89-a45e-c2c37377a8b7)

**Comment by Feiyuyu0503** [comment]
> 我在重启docker后日志显示到这一步就会卡住，网页也无法访问，请问是什么原因 ![IMG_20240225_014734](https://private-user-images.githubusercontent.com/98746227/307540420-4d7ee862-7720-4e89-a45e-c2c37377a8b7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3OTcyMzAsIm5iZiI6MTcwODc5NjkzMCwicGF0aCI6Ii85ODc0NjIyNy8zMDc1NDA0MjAtNGQ3ZWU4NjItNzcyMC00ZTg5LWE0NWUtYzJjMzczNzdhOGI3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDE3NDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzOWJjODE1MTY5Y2M4MWM4ZmQ3NGRiZDUyMWE5MGU0YTdmMGVmNTY3YzUxN2ExOTA3NzI5MWVhMGUxNWVjN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oIeB117ISjBMaj-QpHIVciLV8dq9oG12WvARK54CdF8)

可能是300的超时时间太长了，下载图片的步骤阻塞在那了，我猜测。但是很奇怪为什么下载不下来呢，看起来你的文件权限也没什么问题，不知道系统时间对下载有没有影响，暂时只能瞎猜了

**Comment by Feiyuyu0503** [comment]
简单查询了下上游的相关issue，https://github.com/LonamiWebs/Telethon/issues?q=download_media ，这个问题比较难以复现，大概率是网络问题（无论是用户侧还是tg服务端），有的人反馈重启程序就好了，也有可能是换了个时间重试就好了，https://github.com/LonamiWebs/Telethon/issues/955#issuecomment-413346535 ，你先尝试再跑一遍观察一下吧，再不行挂个代理试试。

**Comment by LHXCxyw** [comment]
应该是网络问题，我设置代理后图片获取成功了

**Comment by santosh-gkg** [comment]
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/150844949/40bf6936-7159-4235-9911-50b5752645f4)
the logs shows this

**Comment by santosh-gkg** [comment]
i had left the group chat id option as it is, does that matters?
