### ISSUE TITLE
看了一下issues，为啥我的tg在组里面需要加上反斜杠/

### ISSUE THREAD

**Issue by shenmadouyaowen** [Feiyuyu0503/free-dall-e-proxy#15]
看了一下issues，为啥我的tg在组里面需要加上反斜杠/,别人的不用？
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/12426724/0eb54a0c-e3d9-43e3-8a6f-fff9d06652dd)

**Comment by Feiyuyu0503** [comment]
你是在说使用本项目的时候需要加/吗？本项目是不需要加/的，其他项目那是看程序内部是如何写的。

**Comment by shenmadouyaowen** [comment]
> 你是在说使用本项目的时候需要加/吗？本项目是不需要加/的，其他项目那是看程序内部是如何写的。

是的，你的项目也要加，不然在组里面没有反应

**Comment by Feiyuyu0503** [comment]
> 看了一下issues，为啥我的tg在组里面需要加上反斜杠/,别人的不用？
> ![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/12426724/0eb54a0c-e3d9-43e3-8a6f-fff9d06652dd)
> 

我懂了。就像图上说的，有两种主要方式：1.如果你是群管理员，那么就直接把机器人设置成管理员。2.如果你不是，那么有以下三种方法。
所以，你把机器人设置成管理员就不需要加/了。区别就是是否可存取消息
![IMG_20240227_095546.jpg](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/32660959/85dd8947-74b7-48b6-b8f0-9f06dca5db05)

**Comment by shenmadouyaowen** [comment]
好的，明白了，谢谢
