### ISSUE TITLE
Something wrong occurs, please retry. If the error persists, please contact the support team.

### ISSUE THREAD

**Issue by LHXCxyw** [Feiyuyu0503/free-dall-e-proxy#18]
dalle3似乎返回不了图片了，tg里提示Something wrong occurs, please retry. If the error persists, please contact the support team.
然后我去coze试了一下，插件过程里有图片输出，但是最终结果输出却没有显示图片
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/98746227/174f0089-4a6b-4b5c-b582-bba5bbb85a18)

**Comment by Feiyuyu0503** [comment]
用户机器人向coze机器人请求的次数超过当前设置模型的上限了。你可以在tg群里用另一个号@coze机器人就可以发现coze机器人还是正常的。
解决方法：
1. 等待次数刷新
2. 去coze网页上切换一个模型，如gpt-4-turbo换成gpt-4
3. 等我之后更新多个coze agents的代码，最近忙没空更新

关于coze的限制，如下：
Regarding message limits, currently the message limits on Coze are:
GPT-4 (8K)：100 interactions/user/day
GPT-4 (128K)：50 interactions/user/day
GPT-3.5 (16K) : 500 interactions/user/day

**Comment by Feiyuyu0503** [comment]
> 用户机器人向coze机器人请求的次数超过当前设置模型的上限了。你可以在tg群里用另一个号@coze机器人就可以发现coze机器人还是正常的。 解决方法：
> 
> 1. 等待次数刷新
> 2. 去coze网页上切换一个模型，如gpt-4-turbo换成gpt-4
> 3. 等我之后更新多个coze agents的代码，最近忙没空更新
> 
> 关于coze的限制，如下： Regarding message limits, currently the message limits on Coze are: GPT-4 (8K)：100 interactions/user/day GPT-4 (128K)：50 interactions/user/day GPT-3.5 (16K) : 500 interactions/user/day

抱歉，似乎当前并不是我说的这种情况。coze可能出现了点问题。

**Comment by Feiyuyu0503** [comment]
已恢复。
