### ISSUE TITLE
coze not giving output for simple prompt

### ISSUE THREAD

**Issue by santosh-gkg** [Feiyuyu0503/free-dall-e-proxy#20]
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/150844949/a40517ed-0702-4d74-a586-dbd9f1c2728c)

**Comment by santosh-gkg** [comment]
i am using it on localhost and my region is india where coze is not available, can that be a issue?

**Comment by Feiyuyu0503** [comment]
> i am using it on localhost and my region is india where coze is not available, can that be a issue?

Just need you to be able to talk to a telegram or discord bot supported by coze

**Comment by santosh-gkg** [comment]
Yeah the telegram bot I created is working nice, I am able to generate images but my localhost setup is showing this error

**Comment by Feiyuyu0503** [comment]
Check if there are images under this path `./data/images`

**Comment by santosh-gkg** [comment]
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/150844949/97d0ae37-3e28-4dd2-bc3c-93dade022050)
nothing here

**Comment by Feiyuyu0503** [comment]
1. check your running logs and maybe this issue is similar to https://github.com/Feiyuyu0503/free-dall-e-proxy/issues/14#issuecomment-1962858708
2. try to turn off `auto suggestion`
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/32660959/2e12a447-c0b0-469b-b793-550d1a5faada)

**Comment by santosh-gkg** [comment]
thank you very much for your support, really appreciated! there was some issue with my telegram_group_id now it's working completely fine
