### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by finalblast** [Feiyuyu0503/free-dall-e-proxy#21]
It seems to be stopped because of the stream.

**Comment by finalblast** [comment]
@Feiyuyu0503 It is now response with 2 messages.

1 is reply_to_msg_id kind of: 

> Sure, here's another image of a chicken for you:

Then 1 another message is the image.

**Comment by finalblast** [comment]
Before:
<img width="375" alt="Screenshot 2024-05-21 at 09 10 47" src="https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/9843565/67bbfefb-ec94-4595-9152-f47baf370822">

After:
<img width="415" alt="Screenshot 2024-05-21 at 09 12 20" src="https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/9843565/fb9fd748-8563-43b7-9c9a-949341e58611">

**Comment by Feiyuyu0503** [comment]
Thank you for your report. It's a known issue. Have you tried to adjust your system prompts, e.g.: please give me an image without any other description texts. And switch the base model to GPT-4 series to follow the prompts better.

**Comment by Feiyuyu0503** [comment]
try this solution： https://github.com/Feiyuyu0503/free-dall-e-proxy/issues/22#issuecomment-2149699945

**Comment by finalblast** [comment]
@Feiyuyu0503 it seems to be working but I am getting error: You have exceeded the daily limit for sending messages to the bot. Please try again later. Any idea?

**Comment by Feiyuyu0503** [comment]
For each telegram account, there is a limit on the number of conversations with coze bots per day.
Multiple telegram accounts will be work.
