### ISSUE TITLE
tg机器人发送消息不再是直接回复图片，导致代理无法获取图片

### ISSUE THREAD

**Issue by LHXCxyw** [Feiyuyu0503/free-dall-e-proxy#22]
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/98746227/3008d6ac-66cc-456c-98ca-2ceb36e289c4)
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/98746227/1a52eaf1-e3ff-4f4b-aa49-645fe1f45532)

tg机器人回复的内容不再是图片，而是先回复文本，再发送单独的图片，这样导致代理没法返回图片内容，仅返回的文本和sorry_cat

**Comment by LHXCxyw** [comment]
这是之前的回复格式
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/98746227/fce879e6-82ca-49e6-af47-2ad37388d6bf)

**Comment by Feiyuyu0503** [comment]
最近忙毕业，之后有空的时候看看怎么处理

**Comment by LHXCxyw** [comment]
感谢

**Comment by Feiyuyu0503** [comment]
一个临时的解决方法，对coze bot的Persona & Prompt设置中添加类似如下的限制
```
- (Most important) Make sure to give me the image directly without replying with any other description texts.
```
我这样设置，观察了2个礼拜左右，比较稳定。

**Comment by LHXCxyw** [comment]
确认是可以了，感谢大佬
