### ISSUE TITLE
反代问题

### ISSUE THREAD

**Issue by 1kFace8aby** [Feiyuyu0503/free-dall-e-proxy#23]
你好请问有办法在这个里面用第三方代理的Azure dalle吗 就是没有key只有代理链接和密码那种

**Comment by Feiyuyu0503** [comment]
不是很明白你的意思，“这个里面”是指本项目？还是lobechat？第三方代理的azure dalle是指one-api/new-api/...那些服务？

**Comment by 1kFace8aby** [comment]
是的，就是这个项目 我不太懂代码 抱歉抱歉

**Comment by 1kFace8aby** [comment]
啊 我在另外一个叫de3u的项目里面找到了解决方案 打扰了 谢谢大佬
