### ISSUE TITLE
tg回复会带上文字

### ISSUE THREAD

**Issue by LHXCxyw** [Feiyuyu0503/free-dall-e-proxy#24]
大佬，还是之前的问题，这次不管怎么改tg里的bot一直都回复一段文本：
![817d11ad824d528a306ff4e971fb4c03](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/98746227/b72e1803-bc17-4951-ba1b-3aff7198cb54)
在coze里调试的时候又是没有文字的，只在tgbot里出现

**Comment by Feiyuyu0503** [comment]
试试更新到最新版
data/.env中新增一个环境变量ADDITION_PROMPT
https://github.com/Feiyuyu0503/free-dall-e-proxy/blob/43c6679d37bfac76f3e77930dad43c1558b85eb3/data/.env.example#L8
