### ISSUE TITLE
Telegram responce time out error

### ISSUE THREAD

**Issue by B21zh** [Feiyuyu0503/free-dall-e-proxy#28]
I have an issue and not really understand what is wrong. 
The server log shows this errors after an atempt to use it "ERROR | Bots.teleClient:send_message:47 - Telegram message sent, but response timeout!", "ERROR | imageGenerationsApi:create_image:72 - Telegram client got invalid response: None" and the bot in the telegram does not give out anything other than a prompt. I tried to access the server using a different methods, but the situation was identical except that I managed to get a link (not in the telegram) to a certain picture: “a cat with a broken vase and the word sorry on top.” After several attempts, there were same errors and the same image is displayed regardless of the prompt

**Comment by Feiyuyu0503** [comment]
`the bot in the telegram does not give out anything other than a prompt.`
The prompt message should be sent by your personal telegram account, and the bot would response it with an image if everything work correctly. see https://github.com/Feiyuyu0503/free-dall-e-proxy/blob/415ce11847e58813d00d1b7699133097b387475d/docs/how_to_configure.md?plain=1#L14

**Comment by B21zh** [comment]
I have checked it and found a misstype in /.env in Api_id, but now after sending a Post request Im getting nothing at all (before there was some message) from bot in telegram and insted of previuos error there is: "WARNING: Invalid HTTP request received." in server log and "curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - П" in window with curl. 

I have done these steps: created coze app and tg bot and put into the tg group, edited /.env, run proxy, edited curl command (https - changed on that one in server log and $KEY to Api_key from /.env), run the curl in another window of git and immediately got current warning.
Before I had no warnings (but there was a misstype in api_id) and the curl was just waiting untill the error "time responce." During this time I was trying to comunicate with tg bot in a lot of ways but nothing happened.

I guess Im doing something wrong but unfortunately Im not a true programmer, so I dont really understand how and where to start the process nor what may be the cause of those errors. I would really appreciate it if you will say what Im doing wrong. 

PS: I don know how and why, but there were a few times when I have got a message after the curl command ended: "Picture doesnt met the coze rules, remember no violence ..." or something like that for curl prompt - draw a box

**Comment by Feiyuyu0503** [comment]
Firstly, you can manually @bot on the official telegram client instead of using the program, send your request and see if the bot replies properly.

**Comment by B21zh** [comment]
Im sorry for being so problematic, but I really need and want to make it work. 

Today I have decided to switch to discord and now things look better. I manually @ bot as you said to check it and it was just a pure coze agent, so it gave me 3 pictures and I ran out of credits. Also, when I using a curl now, my personal ds account is automatically @ bot and sending the prompt in ds, but it still communicating with coze dirrectly as if I would have nothing than a programm that @ bot from the outside of ds, so I again got: "get coze premium." Further more, the proxy got the error: no responce

**Comment by Feiyuyu0503** [comment]
Switch your base model to gpt-3.5 turbo or gpt-4o-mini on the coze platform and you will get more calls.

**Comment by B21zh** [comment]
Finally everything works, so there is no more errors in proxy and curl return the url on a picture (for some reason. maybe the coze agent was setup wong and when i changed it to 3.5 it was corrected). However I still have a slight misunderstanding about whether there should be a daily limit of pictures or not, because I again ran into it for no obvious (to me) reasons, as everything works fine now. If there should be a limit, could you possibly explain why proxy is needed here if coze agent can work without it (i could get a picture from coze, while proxy was off)

**Comment by Feiyuyu0503** [comment]
The usage of `Curl `is just an example. You can use this API proxy for image generation in any other scenarios compatible with OpenAI DALL-E API.

**Comment by B21zh** [comment]
Ok, got it
