### ISSUE TITLE
建议添加终止生成功能以提高用户体验并避免生成失败或卡顿问题

### ISSUE THREAD

**Issue by Raimbaulty** [Feiyuyu0503/free-dall-e-proxy#3]
我很感谢您提供的项目，但我注意到了一个潜在的改进点。在使用过程中，有时会遇到生成时间过长或者生成失败的情况，这可能会导致用户体验下降或者让用户感到困惑。因此，我建议在生成过程中添加一个终止按钮，这样用户可以主动中止生成过程，避免长时间无响应或者生成失败而导致的卡住情况。

**Comment by Feiyuyu0503** [comment]
好的，非常感谢您的建议，后面还有很多需要完善的地方。项目的主要用途还是api调用，附带了一个简易的webui只是用于快速测试api和查看api文档，webui后面我会再完善一下，包括添加您的建议功能。
生成时间过长是一个已知现象，因为主要还是依赖coze的响应速度。coze应该还是比较稳定的，我目前还没遇到多少生成失败的case，如果您是尝试了自己部署，遇到生成失败的情况，可能是没有成功触发coze的dall-e-3插件，这个需要调prompt，今天我会写一个我在coze上设置prompt的文档。

**Comment by Raimbaulty** [comment]
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/29273042/8084900c-9e59-4d97-93e3-e2c0c111600e)
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/29273042/f34ee417-72f4-4357-8fcd-74f57384368a)
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/29273042/df8108ae-969f-433f-8c83-e3f80329cacf)

这是我遇到的部分情况，我这里失败的情况蛮普遍的......

**Comment by Feiyuyu0503** [comment]
> ![image](https://private-user-images.githubusercontent.com/29273042/299888932-8084900c-9e59-4d97-93e3-e2c0c111600e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDg1MDQsIm5iZiI6MTcwNjI0ODIwNCwicGF0aCI6Ii8yOTI3MzA0Mi8yOTk4ODg5MzItODA4NDkwMGMtOWU1OS00ZDk3LTkzZTMtZTJjMGMxMTE2MDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA1NTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMjk5YTgwMTUxNjZiZjJkMGVkZTM4MjM4NDM5MTYyMDY1ZWI1NTNjZjk0NzAwYTFlM2U3ZDA5MDA5NTJlNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R0rpATPNvUV_RrkiKPkyeQtRxtTihieoAUL8Au3n8WI) ![image](https://private-user-images.githubusercontent.com/29273042/299889075-f34ee417-72f4-4357-8fcd-74f57384368a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDg1MDQsIm5iZiI6MTcwNjI0ODIwNCwicGF0aCI6Ii8yOTI3MzA0Mi8yOTk4ODkwNzUtZjM0ZWU0MTctNzJmNC00MzU3LThmY2QtNzRmNTczODQzNjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA1NTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZmU0NGUzMDI2ZGU5NjRhNzdiNTYzZDFmOGViNmE1YTlhY2IwNDBjZjMxOGI3N2NkNWVkMGI2M2MzOWNkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jieFOVtprABOd_zu3PNcvau0fkEKmyIiR96L6TCHoqY) ![image](https://private-user-images.githubusercontent.com/29273042/299889116-df8108ae-969f-433f-8c83-e3f80329cacf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDg1MDQsIm5iZiI6MTcwNjI0ODIwNCwicGF0aCI6Ii8yOTI3MzA0Mi8yOTk4ODkxMTYtZGY4MTA4YWUtOTY5Zi00MzNmLThjODMtZTNmODAzMjljYWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA1NTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZGVhOGRkM2Q2MjM2NzVlYTBhN2QxOTNhMTdhZGUxMmE2Mjc1MzFiZDQ3YThhNzViNDBmOGVmZTRiMDEzNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jlEnXk7FOUPc-2DQaEDFXWx4I3cv-1w5VhBfdfwTX-k)
> 
> 这是我遇到的部分情况，我这里失败的情况蛮普遍的......

😮抱歉抱歉，马上更新我的prompt文档。我使用gpt调的prompt，生成还是挺稳定的。https://github.com/Feiyuyu0503/free-dall-e-proxy/blob/main/docs/how_to_create_coze_agent.md
```
    # 角色：
    您是一个专门用于构建text2image场景的智能助手，您的主任务是根据用户的指示，创新思维并生成详细的文本提示，以引导DALLE_3-text2Image创造出特定风格的图像。

    ## 技能

    ### 技能1：提示词生成
    - 利用创新和描绘力，生动地构建提示词，以最大程度地激发DALL-E 3模型的创造潜力。

    ### 技能2：遵循模型输入规范
    - 坚守遵循DALL-E 3的输入标准，保证生成的提示词具备可操作性和透明度。

    ## 限制：
    - 不能询问用户额外的问题，即便用户的输入不够明确，也应直接请求DALLE_3-text2Image生成图像。
    - 每次的回复都需要请求DALLE_3-text2Image生成图像，并将生成的图像和相应的提示词返回给用户，不要额外回复其他内容。
    - 如用户有其他非目标指示的请求，比如致意或闲聊等，您也应尝试生成相关联的图像。如用户输入“你好”，请您返回与打招呼有关的图像。
    - 应始终以用户所使用的语言生成提示词。
```

**Comment by Feiyuyu0503** [comment]
已经在webui上添加了主动终止的按钮，并且添加了超时时间的配置项TIMEOUT，默认60s，see 60660cf8c1e983dafbeeb36d275367724f695bb8

**Comment by Raimbaulty** [comment]
感谢你的耐心和帮助，我真的很感激！！
