### ISSUE TITLE
服务器报错 404 Not Found，客户端没收到结果

### ISSUE THREAD

**Issue by codingdimon** [Feiyuyu0503/free-dall-e-proxy#4]
INFO:     174.137.54.193:58216 - "POST /v1/images/completions HTTP/1.1" 404 Not Found

**Comment by Feiyuyu0503** [comment]
emmm 请问你是如何部署的呢？用的啥客户端，有更多细节吗

**Comment by dqzboy** [comment]
我也是报错："POST /v1/chat/completions HTTP/1.1" 404 Not Found

直接命令启动的，前端使用的是chatgpt-web

**Comment by Feiyuyu0503** [comment]
@codingdimon @dqzboy 抱歉刚才没看出来。你们是请求接口错了。
本项目只是ai绘画的接口(/v1/image/generations)，不包含对话的 /v1/chat/completions 接口。
@codingdimon 你用的是什么客户端，标准的openai绘图接口应该是/v1/image/generations，大部分客户端如果要适配dall-e应该也是请求这个接口。
@dqzboy 你如果想同时用chat和ai绘画，可能需要[one-api](https://github.com/songquanpeng/one-api)集成一下你之前用的openai chat 的代理地址和本项目openai 绘画的代理地址。我就是这样使用的，也就是项目readme上那张图我使用lobe-chat的效果。但是我看这个[chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)好像本身并不支持绘图模型接口的调用

**Comment by Feiyuyu0503** [comment]
https://platform.openai.com/docs/api-reference/images/create
![image](https://github.com/Feiyuyu0503/free-dall-e-proxy/assets/32660959/e7e2b3ac-d168-4ba3-92eb-67b06a279361)

**Comment by dqzboy** [comment]
> @codingdimon @dqzboy 抱歉刚才没看出来。你们是请求接口错了。 本项目只是ai绘画的接口(/v1/images/generations)，不包含对话的 /v1/chat/completions 接口。 @codingdimon 你用的是什么客户端，标准的openai绘图接口应该是/v1/images/generations，大部分客户端如果要适配dall-e应该也是请求这个接口。 @dqzboy 你如果想同时用chat和ai绘画，可能需要[one-api](https://github.com/songquanpeng/one-api)集成一下你之前用的openai chat 的代理地址和本项目openai 绘画的代理地址。我就是这样使用的，也就是项目readme上那张图我使用lobe-chat的效果。但是我看这个[chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)好像本身并不支持绘图模型接口的调用

好的，明白了，谢谢
