### ISSUE TITLE
在render部署项目报错

### ISSUE THREAD

**Issue by WangCghy** [Feiyuyu0503/free-dall-e-proxy#6]
![报错](https://image.wanc.eu.org/file/26f09edca2029ea5637bd.png)

启动失败
，提示确认手机号

**Comment by Feiyuyu0503** [comment]
1.如果你使用telegram，那么你需要登录你的tg账号，来和coze的tg bot交互。原因见 https://github.com/Feiyuyu0503/free-dall-e-proxy/issues/2#issuecomment-1911299555 并且也并不清楚使用程序来登录tg账号是否会有账号封禁的风险，所以我有义务提醒一下，不过至少我现在每天几百次的请求还没有出现问题。
所以如果你一定要在render部署并使用telegram，我已知的方法有两个
（1）升级render的付费账号，这样可以使用web shell来输入你的telegram登录账号和登录验证码（我平时并不使用render，不清楚是否有其他方法可以帮助你输入验证码）
（2）先在你本地机器或云服务器上登录成功telegram，并将session文件保存下来，给到render登录使用。可以在本地/云服务器使用本项目来登录一次，或者之后我可以提供一个小脚本来登录并获取到session。

2.不启用telegram，换用discord。discord的机器人与机器人之间可以对话。

**Comment by Feiyuyu0503** [comment]
@WangCghy 额外的telegram登录脚本在这。https://gist.github.com/Feiyuyu0503/d0c74f56df0de925a021d1b6004c4e88
